In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import lightning as L

from lightning import LightningDataModule

In [3]:
import polars as pl

In [9]:
annotations = pl.read_csv("./egyptian_fruit_bat_annotated/Annotations.csv")

In [10]:
better_annotations = pl.read_csv("./egyptian_fruit_bat_annotated/better_annotations.csv")

In [ ]:
.write_csv("./egyptian_fruit_bat_annotated/annotations.csv")

In [44]:
sub = better_annotations.select(
    [
        pl.col("Emitter").abs(),
        pl.col("File name"),
        pl.col("File folder")
    ]
).filter(
    pl.col("Emitter") != 0
)

In [71]:
sub_sub = sub.filter(
    pl.col("Emitter").is_in([215, 231, 211, 216, 230, 220, 210, 226, 221, 207, 228, 208])
)

In [72]:
sub_sub.write_csv("./egyptian_fruit_bat_annotated/annotations.csv")

In [73]:
sub_sub

shape: (60_286, 3)
┌─────────┬────────────────────────┬─────────────┐
│ Emitter ┆ File name              ┆ File folder │
│ ---     ┆ ---                    ┆ ---         │
│ i64     ┆ str                    ┆ str         │
╞═════════╪════════════════════════╪═════════════╡
│ 228     ┆ 121001000728041793.WAV ┆ files201    │
│ 228     ┆ 121001000733958794.WAV ┆ files201    │
│ 228     ┆ 121001000740457796.WAV ┆ files201    │
│ 228     ┆ 121001000744199797.WAV ┆ files201    │
│ 228     ┆ 121001000754583800.WAV ┆ files201    │
│ …       ┆ …                      ┆ …           │
│ 208     ┆ 140219102458100432.WAV ┆ files224    │
│ 208     ┆ 140219115758154436.WAV ┆ files224    │
│ 207     ┆ 140219115800624437.WAV ┆ files224    │
│ 215     ┆ 140219120336957438.WAV ┆ files224    │
│ 207     ┆ 140219120345355439.WAV ┆ files224    │
└─────────┴────────────────────────┴─────────────┘

In [70]:
sub["Emitter"].value_counts().filter(
    pl.col("Emitter").is_in([215, 231, 211, 216, 230, 220, 210, 226, 221, 207, 228, 208])
)

shape: (12, 2)
┌─────────┬───────┐
│ Emitter ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 228     ┆ 2660  │
│ 207     ┆ 2980  │
│ 226     ┆ 3286  │
│ 230     ┆ 5735  │
│ 208     ┆ 2459  │
│ …       ┆ …     │
│ 231     ┆ 7354  │
│ 216     ┆ 6160  │
│ 211     ┆ 6168  │
│ 220     ┆ 4007  │
│ 221     ┆ 3149  │
└─────────┴───────┘

In [60]:
sub["Emitter"].value_counts().select(
    pl.col("Emitter").gather(pl.arg_sort_by("count"))
).to_numpy().ravel()[::-1][:12]

array([215, 231, 211, 216, 230, 220, 210, 226, 221, 207, 228, 208])

In [52]:
sub["Emitter"].value_counts().arg_sort_by("count")

AttributeError: 'DataFrame' object has no attribute 'arg_sort_by'

In [ ]:
chosen = better_annotations.select(
    [
        pl.col("Emitter").abs(),
        pl.col("File name"),
        pl.col("File folder")
    ]
).filter(
    pl.col("Emitter") != 0
)["Emitter"].value_counts()["count"].arg_sort().to_numpy()

In [75]:
sub_sub.select(
    [
        pl.col("Emitter").rank("dense") - 1
    ]
).to_torch().ravel().unique()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
labels.unique()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40])

In [12]:
better_annotations

shape: (91_080, 13)
┌───────┬────────┬─────────┬───────────┬───┬────────┬────────────┬───────────────────┬─────────────┐
│       ┆ FileID ┆ Emitter ┆ Addressee ┆ … ┆ Start  ┆ End sample ┆ File name         ┆ File folder │
│ ---   ┆ ---    ┆ ---     ┆ ---       ┆   ┆ sample ┆ ---        ┆ ---               ┆ ---         │
│ i64   ┆ i64    ┆ i64     ┆ i64       ┆   ┆ ---    ┆ i64        ┆ str               ┆ str         │
│       ┆        ┆         ┆           ┆   ┆ i64    ┆            ┆                   ┆             │
╞═══════╪════════╪═════════╪═══════════╪═══╪════════╪════════════╪═══════════════════╪═════════════╡
│ 0     ┆ 7      ┆ 118     ┆ 0         ┆ … ┆ 1      ┆ 336720     ┆ 12060100213205500 ┆ files101    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 8.WAV             ┆             │
│ 1     ┆ 11     ┆ 0       ┆ 0         ┆ … ┆ 1      ┆ 787280     ┆ 12060100234486201 ┆ files101    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 3.WAV             ┆             │
│ 2     ┆ 12     ┆ 118     ┆ 0         ┆ … ┆ 1      ┆ 566096     ┆ 12060100373453903 ┆ files101    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 5.WAV             ┆             │
│ 3     ┆ 15     ┆ 0       ┆ 0         ┆ … ┆ 1      ┆ 402256     ┆ 12060100440261205 ┆ files101    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 2.WAV             ┆             │
│ 4     ┆ 20     ┆ 0       ┆ 0         ┆ … ┆ 1      ┆ 394064     ┆ 12060100514781308 ┆ files101    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 4.WAV             ┆             │
│ …     ┆ …      ┆ …       ┆ …         ┆ … ┆ …      ┆ …          ┆ …                 ┆ …           │
│ 91075 ┆ 293223 ┆ -208    ┆ -221      ┆ … ┆ 1      ┆ 877392     ┆ 14021910245810043 ┆ files224    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 2.WAV             ┆             │
│ 91076 ┆ 293230 ┆ 208     ┆ 221       ┆ … ┆ 1      ┆ 598864     ┆ 14021911575815443 ┆ files224    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 6.WAV             ┆             │
│ 91077 ┆ 293232 ┆ 207     ┆ 221       ┆ … ┆ 1      ┆ 336720     ┆ 14021911580062443 ┆ files224    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 7.WAV             ┆             │
│ 91078 ┆ 293234 ┆ -215    ┆ -221      ┆ … ┆ 1      ┆ 320336     ┆ 14021912033695743 ┆ files224    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 8.WAV             ┆             │
│ 91079 ┆ 293235 ┆ 207     ┆ 221       ┆ … ┆ 1      ┆ 1852240    ┆ 14021912034535543 ┆ files224    │
│       ┆        ┆         ┆           ┆   ┆        ┆            ┆ 9.WAV             ┆             │
└───────┴────────┴─────────┴───────────┴───┴────────┴────────────┴───────────────────┴─────────────┘

In [97]:
from src.data.bats_datamodule import BatsDataModule

In [106]:
data = BatsDataModule(
    data_dir="/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats",
    audio_fname="audio",
    annotations_fname="annotations.csv",
)

In [107]:
data.setup()

In [108]:
train = data.train_dataloader()

In [109]:
len(train)

125

In [ ]:
df.with_columns(
    pl.col("Color").rank("dense") - 1
)

In [110]:
for x, y in train:
    print(x.shape, y.shape)
    print(y)
    break

torch.Size([64, 3, 256, 257]) torch.Size([64])
tensor([220, 111, 215, 220, 226, 215, 216, 216, 228, 216, 231, 230, 111, 210,
        231, 211, 111, 216, 111, 231, 210, 220, 231, 216, 210, 220, 226, 216,
        211, 230, 210, 228, 226, 216, 220, 111, 228, 215, 228, 210, 111, 215,
        216, 230, 226, 215, 216, 211, 230, 231, 230, 230, 228, 226, 216, 211,
        228, 220, 226, 215, 111, 228, 230, 210])

In [72]:
torchaudio.load("/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats/audio/10056.wav")[0].shape

torch.Size([1, 410447])

In [111]:
annotations = pl.read_csv("/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats/annotations.csv")

In [121]:
annotations.select(
    [
        pl.col("Emitter").rank("dense") - 1
    ]
).to_torch().ravel()

tensor([4, 3, 4,  ..., 0, 0, 0])

In [112]:
annotations

shape: (10_000, 2)
┌─────────┬───────────┐
│ Emitter ┆ File Name │
│ ---     ┆ ---       │
│ i64     ┆ str       │
╞═════════╪═══════════╡
│ 216     ┆ 69809.wav │
│ 215     ┆ 71889.wav │
│ 216     ┆ 46690.wav │
│ 230     ┆ 85411.wav │
│ 215     ┆ 45609.wav │
│ …       ┆ …         │
│ 111     ┆ 33297.wav │
│ 111     ┆ 26880.wav │
│ 111     ┆ 24407.wav │
│ 111     ┆ 22549.wav │
│ 111     ┆ 15217.wav │
└─────────┴───────────┘

In [8]:
annotations.select(
    [
        pl.col("Emitter").unique_counts(),
    ]
)

shape: (10, 1)
┌─────────┐
│ Emitter │
│ ---     │
│ u32     │
╞═════════╡
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
└─────────┘